name: store-generated-artifacts
on: 
  push:
    branches:
      - main
      - master
      - feat/**
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first steps
        run: echo "job started"
      - name: checkout branches
        uses: actions/checkout@v4
      - name: store artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-first-artifact
          path: |
            ./src
            package.json
      - name: final part
        run: echo "collected the artifact" 
            
    