name: job-ouputs
on: 
  push:
    branches:
      - main
      - 'dev-*'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      script-file: ${{steps.job-output.outputs.script-file}}
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: build the repo
        run: npm run build
      - name: clone a filename from dist
        id: job-output
        run: find dist/assets -name "*.js" -type f -execdir echo "script-file={}" \; >> $GITHUB_OUTPUT
      - name: completed
        run: echo "job -completed artifact saved"
      - name: echo output from step-2
        run: echo "${{steps.job-output.outputs.script-file}}"
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: first step deployement
        run: echo "${{needs.build.outputs.script-file}}"
        
    